sudo apt-get remove -y adwaita-icon-theme \
apparmor \
apt \
apt-transport-https \
aspnetcore-runtime-2.1 \
aspnetcore-runtime-3.1 \
aspnetcore-runtime-5.0 \
aspnetcore-runtime-6.0 \
aspnetcore-targeting-pack-3.1 \
aspnetcore-targeting-pack-5.0 \
aspnetcore-targeting-pack-6.0 \
autoconf \
automake \
autotools-dev \
base-files \
base-passwd \
bash \
bash-completion \
bazel \
bc \
bind9-dnsutils \
bind9-host \
bind9-libs \
binfmt-support \
binutils \
binutils-common \
binutils-x86-64-linux-gnu \
bison \
bridge-utils \
bsdextrautils \
bsdutils \
build-essential \
bzip2 \
ca-certificates \
ca-certificates-java \
cgroup-tools \
clangd-9 \
cmake-data \
containerd.io \
coreutils \
cpio \
cpp \
cpp-10 \
cron \
curl \
dash \
dbus \
dbus-user-session \
debconf \
debian-archive-keyring \
debianutils \
diffutils \
dirmngr \
distro-info-data \
dmsetup \
dnsmasq-base \
dnsutils \
docker-ce \
docker-ce-cli \
docker-ce-rootless-extras \
docker-scan-plugin \
dotnet-apphost-pack-3.1 \
dotnet-apphost-pack-5.0 \
dotnet-apphost-pack-6.0 \
dotnet-host \
dotnet-hostfxr-2.1 \
dotnet-hostfxr-3.1 \
dotnet-hostfxr-5.0 \
dotnet-hostfxr-6.0 \
dotnet-runtime-2.1 \
dotnet-runtime-3.1 \
dotnet-runtime-5.0 \
dotnet-runtime-6.0 \
dotnet-runtime-deps-2.1 \
dotnet-runtime-deps-3.1 \
dotnet-runtime-deps-5.0 \
dotnet-runtime-deps-6.0 \
dotnet-sdk-2.1 \
dotnet-sdk-3.1 \
dotnet-sdk-5.0 \
dotnet-sdk-6.0 \
dotnet-targeting-pack-3.1 \
dotnet-targeting-pack-5.0 \
dotnet-targeting-pack-6.0 \
dpkg \
dpkg-dev \
e2fsprogs \
emacs-bin-common \
emacs-common \
emacs-nox \
emacsen-common \
file \
findutils \
fontconfig \
fontconfig-config \
fonts-dejavu-core \
fuse \
g++ \
g++-10 \
gcc \
gcc-10 \
gcc-10-base \
gcc-9-base \
gcsfuse \
gdb \
gettext \
gettext-base \
gh \
gir1.2-glib-2.0 \
gir1.2-packagekitglib-1.0 \
git \
git-man \
gnupg \
gnupg-l10n \
gnupg-utils \
gnupg2 \
google-cloud-sdk-app-engine-go \
google-cloud-sdk-app-engine-java \
google-cloud-sdk-app-engine-python \
google-cloud-sdk-app-engine-python-extras \
google-cloud-sdk-datastore-emulator \
google-cloud-sdk-pubsub-emulator \
google-cloud-sdk-skaffold \
gpg \
gpg-agent \
gpg-wks-client \
gpg-wks-server \
gpgconf \
gpgsm \
gpgv \
graphviz \
grep \
groff-base \
gtk-update-icon-cache \
gzip \
hdf5-helpers \
hicolor-icon-theme \
hostname \
htop \
init-system-helpers \
initramfs-tools \
initramfs-tools-core \
install-info \
iproute2 \
iptables \
iso-codes \
java-common \
jq \
klibc-utils \
kmod \
kubectl \
less \
lib32gcc-s1 \
lib32stdc++6 \
libacl1 \
libaec-dev \
libaec0 \
libann0 \
libapparmor1 \
libapt-pkg6.0 \
libarchive13 \
libargon2-1 \
libasan6 \
libasound2 \
libasound2-data \
libassuan0 \
libasyncns0 \
libatk-bridge2.0-0 \
libatk-wrapper-java \
libatk-wrapper-java-jni \
libatk1.0-0 \
libatk1.0-data \
libatomic1 \
libatspi2.0-0 \
libattr1 \
libaudit-common \
libaudit1 \
libavahi-client-dev \
libavahi-client3 \
libavahi-common-data \
libavahi-common-dev \
libavahi-common3 \
libbabeltrace1 \
libbinutils \
libblkid-dev \
libblkid1 \
libboost-regex1.74.0 \
libbpf0 \
libbrotli1 \
libbsd0 \
libbz2-1.0 \
libbz2-dev \
libc-bin \
libc-dev-bin \
libc-l10n \
libc6 \
libc6-dbg \
libc6-dev \
libc6-i386 \
libcairo2 \
libcap-ng0 \
libcap2 \
libcap2-bin \
libcapstone4 \
libcbor0 \
libcc1-0 \
libcdt5 \
libcgraph6 \
libcgroup1 \
libclang-common-9-dev \
libcom-err2 \
libcrypt-dev \
libcrypt1 \
libcryptsetup12 \
libctf-nobfd0 \
libctf0 \
libcups2 \
libcurl3-gnutls \
libcurl4 \
libdatrie1 \
libdb5.3 \
libdbus-1-3 \
libdbus-1-dev \
libdebconfclient0 \
libdebuginfod1 \
libdeflate0 \
libdevmapper1.02.1 \
libdpkg-perl \
libdrm-amdgpu1 \
libdrm-common \
libdrm-intel1 \
libdrm-nouveau2 \
libdrm-radeon1 \
libdrm2 \
libdw1 \
libedit2 \
libelf1 \
liberror-perl \
libestr0 \
libevent-2.0-5 \
libexpat1 \
libexpat1-dev \
libext2fs2 \
libfastjson4 \
libffi-dev \
libffi7 \
libfido2-1 \
libflac8 \
libfontconfig1 \
libfontenc1 \
libfreetype6 \
libfribidi0 \
libfstrm0 \
libfuse2 \
libgcc-10-dev \
libgcc-s1 \
libgcrypt20 \
libgd3 \
libgdbm-compat4 \
libgdbm-dev \
libgdbm6 \
libgdk-pixbuf-2.0-0 \
libgdk-pixbuf2.0-common \
libgfortran5 \
libgif7 \
libgirepository-1.0-1 \
libgl1 \
libgl1-mesa-dri \
libglapi-mesa \
libglib2.0-0 \
libglib2.0-bin \
libglib2.0-data \
libglib2.0-dev \
libglib2.0-dev-bin \
libglvnd0 \
libglx-mesa0 \
libglx0 \
libgmp-dev \
libgmp10 \
libgmpxx4ldbl \
libgnutls30 \
libgomp1 \
libgpg-error0 \
libgpm2 \
libgraphite2-3 \
libgssapi-krb5-2 \
libgtk2.0-0 \
libgtk2.0-common \
libgts-0.7-5 \
libgvc6 \
libgvpr2 \
libharfbuzz0b \
libhdf5-103-1 \
libhdf5-cpp-103-1 \
libhdf5-dev \
libhdf5-fortran-102 \
libhdf5-hl-100 \
libhdf5-hl-cpp-100 \
libhdf5-hl-fortran-100 \
libhogweed6 \
libice6 \
libicu67 \
libidn11 \
libidn2-0 \
libio-pty-perl \
libip4tc2 \
libip6tc2 \
libipc-run-perl \
libipt2 \
libisl23 \
libitm1 \
libjansson4 \
libjbig0 \
libjpeg-dev \
libjpeg62-turbo \
libjpeg62-turbo-dev \
libjq1 \
libjson-c5 \
libjson-perl \
libjsoncpp24 \
libk5crypto3 \
libkeyutils1 \
libklibc \
libkmod2 \
libkrb5-3 \
libkrb5support0 \
libksba8 \
liblab-gamut1 \
liblcms2-2 \
libldap-2.4-2 \
libllvm11 \
libllvm9 \
liblmdb0 \
liblognorm5 \
liblsan0 \
libltdl7 \
liblttng-ust-ctl4 \
liblttng-ust0 \
liblua5.2-0 \
liblxc1 \
liblz4-1 \
liblzma-dev \
liblzma5 \
libmagic-mgc \
libmagic1 \
libmaxminddb0 \
libmd0 \
libmnl0 \
libmount-dev \
libmount1 \
libmpc3 \
libmpdec3 \
libmpfr6 \
libncurses-dev \
libncurses5-dev \
libncurses6 \
libncursesw6 \
libnetfilter-conntrack3 \
libnettle8 \
libnfnetlink0 \
libnftables1 \
libnftnl11 \
libnghttp2-14 \
libnl-3-200 \
libnl-genl-3-200 \
libnpth0 \
libnsl-dev \
libnsl2 \
libnspr4 \
libnss-systemd \
libnss3 \
libnuma1 \
libogg0 \
libonig5 \
libopus0 \
libp11-kit0 \
libpackagekit-glib2-18 \
libpam-modules \
libpam-modules-bin \
libpam-runtime \
libpam-systemd \
libpam0g \
libpango-1.0-0 \
libpangocairo-1.0-0 \
libpangoft2-1.0-0 \
libpathplan4 \
libpciaccess0 \
libpcre16-3 \
libpcre2-16-0 \
libpcre2-32-0 \
libpcre2-8-0 \
libpcre2-dev \
libpcre2-posix2 \
libpcre3 \
libpcre3-dev \
libpcre32-3 \
libpcrecpp0v5 \
libpcsclite1 \
libperl5.32 \
libpipeline1 \
libpixman-1-0 \
libpng16-16 \
libpq-dev \
libpq5 \
libprocps8 \
libprotobuf-c1 \
libprotobuf23 \
libprotoc23 \
libpsl5 \
libpulse-dev \
libpulse-mainloop-glib0 \
libpulse0 \
libpython2-stdlib \
libpython2.7 \
libpython2.7-dev \
libpython2.7-minimal \
libpython2.7-stdlib \
libpython3-stdlib \
libpython3.9 \
libpython3.9-dev \
libpython3.9-minimal \
libpython3.9-stdlib \
libquadmath0 \
libreadline-dev \
libreadline8 \
librhash0 \
librtmp1 \
libruby2.7 \
libsasl2-2 \
libsasl2-modules-db \
libseccomp2 \
libsecret-1-0 \
libsecret-common \
libselinux1 \
libselinux1-dev \
libsemanage-common \
libsemanage1 \
libsensors-config \
libsensors5 \
libsepol1 \
libsepol1-dev \
libsigsegv2 \
libslang2 \
libslirp0 \
libsm6 \
libsmartcols1 \
libsndfile1 \
libsodium23 \
libsource-highlight-common \
libsource-highlight4v5 \
libsqlite3-0 \
libsqlite3-dev \
libss2 \
libssh2-1 \
libssl-dev \
libssl1.1 \
libstdc++-10-dev \
libstdc++6 \
libsystemd0 \
libsz2 \
libtasn1-6 \
libtcl8.6 \
libthai-data \
libthai0 \
libtiff5 \
libtime-duration-perl \
libtimedate-perl \
libtinfo5 \
libtinfo6 \
libtirpc-common \
libtirpc-dev \
libtirpc3 \
libtool \
libtsan0 \
libubsan1 \
libuchardet0 \
libudev1 \
libunistring2 \
libunwind8 \
liburcu6 \
libutempter0 \
libuuid1 \
libuv1 \
libvorbis0a \
libvorbisenc2 \
libvulkan1 \
libwebp6 \
libwrap0 \
libx11-6 \
libx11-data \
libx11-xcb1 \
libxau6 \
libxaw7 \
libxcb-dri2-0 \
libxcb-dri3-0 \
libxcb-glx0 \
libxcb-present0 \
libxcb-render0 \
libxcb-shape0 \
libxcb-shm0 \
libxcb-sync1 \
libxcb-xfixes0 \
libxcb1 \
libxcomposite1 \
libxcursor1 \
libxdamage1 \
libxdmcp6 \
libxext6 \
libxfixes3 \
libxft2 \
libxi6 \
libxinerama1 \
libxkbfile1 \
libxml2 \
libxmu6 \
libxmuu1 \
libxpm4 \
libxrandr2 \
libxrender1 \
libxshmfence1 \
libxslt1.1 \
libxt6 \
libxtables12 \
libxtst6 \
libxv1 \
libxxf86dga1 \
libxxf86vm1 \
libxxhash0 \
libyaml-0-2 \
libyaml-dev \
libz3-4 \
libzstd1 \
linux-base \
linux-libc-dev \
locales \
login \
logsave \
lsb-base \
lsb-release \
lxc \
lynx \
lynx-common \
m4 \
mailcap \
make \
man-db \
manpages \
mawk \
mc \
mc-data \
media-types \
mercurial \
mercurial-common \
mime-support \
moreutils \
mount \
mysql-apt-config \
mysql-client \
mysql-common \
mysql-community-client \
mysql-community-client-core \
mysql-community-client-plugins \
nano \
ncurses-base \
ncurses-bin \
net-tools \
netbase \
netstandard-targeting-pack-2.1 \
nftables \
openjdk-11-jdk \
openjdk-11-jdk-headless \
openjdk-11-jre \
openjdk-11-jre-headless \
openjdk-17-jdk \
openjdk-17-jdk-headless \
openjdk-17-jre \
openjdk-17-jre-headless \
openjdk-8-jdk \
openjdk-8-jdk-headless \
openjdk-8-jre \
openjdk-8-jre-headless \
openssh-client \
openssh-server \
openssh-sftp-server \
openssl \
packages-microsoft-prod \
packer \
parallel \
passwd \
patch \
perl \
perl-base \
perl-modules-5.32 \
pgdg-keyring \
php-common \
php-pear \
php7.2-bcmath \
php7.2-cgi \
php7.2-cli \
php7.2-common \
php7.2-dev \
php7.2-json \
php7.2-mbstring \
php7.2-mysql \
php7.2-opcache \
php7.2-readline \
php7.2-xml \
pigz \
pinentry-curses \
pkg-config \
postgresql \
postgresql-14 \
postgresql-client \
postgresql-client-14 \
postgresql-client-common \
postgresql-common \
powershell \
procps \
protobuf-compiler \
psmisc \
python-apt-common \
python-pip-whl \
python-pkg-resources \
python-setuptools \
python2 \
python2-minimal \
python2.7 \
python2.7-dev \
python2.7-minimal \
python3 \
python3-apt \
python3-dbus \
python3-distutils \
python3-gi \
python3-lib2to3 \
python3-minimal \
python3-pip \
python3-pkg-resources \
python3-pycurl \
python3-setuptools \
python3-software-properties \
python3-venv \
python3-wheel \
python3.9 \
python3.9-dev \
python3.9-minimal \
python3.9-venv \
qemu-user \
qemu-user-static \
rake \
readline-common \
rsyslog \
ruby \
ruby-dev \
ruby-minitest \
ruby-net-telnet \
ruby-power-assert \
ruby-rubygems \
ruby-test-unit \
ruby-xmlrpc \
ruby2.7 \
ruby2.7-dev \
rubygems-integration \
runit-helper \
sed \
sensible-utils \
shared-mime-info \
shtool \
slirp4netns \
software-properties-common \
sqlite3 \
ssl-cert \
strace \
sudo \
supervisor \
sysstat \
systemd \
systemd-sysv \
systemd-timesyncd \
sysvinit-utils \
tar \
telnet \
terraform \
tmux \
tzdata \
ucf \
udev \
unzip \
util-linux \
uuid-dev \
vim \
vim-common \
vim-nox \
vim-runtime \
wget \
whois \
x11-common \
x11-utils \
xxd \
xz-utils \
zip \
zlib1g \
zlib1g-dev
