sudo apt-get remove -y google-cloud-sdk-gke-gcloud-auth-plugin
sudo apt-get remove -y aspnetcore-targeting-pack-3.1
sudo apt-get remove -y dotnet-apphost-pack-5.0
sudo apt-get remove -y dotnet-apphost-pack-6.0
sudo apt-get remove -y libhdf5-dev
sudo apt-get remove -y libc6-dbg
sudo apt-get remove -y aspnetcore-targeting-pack-6.0
sudo apt-get remove -y libc6-i386
sudo apt-get remove -y aspnetcore-targeting-pack-5.0
sudo apt-get remove -y libc6
sudo apt-get remove -y libpython2.7-dev
sudo apt-get remove -y docker-scan-plugin
sudo apt-get remove -y libgcc-10-dev
sudo apt-get remove -y mysql-community-client-plugins
sudo apt-get remove -y google-cloud-sdk-cbt
sudo apt-get remove -y binutils-common
sudo apt-get remove -y google-cloud-sdk-cloud-run-proxy
sudo apt-get remove -y mercurial-common
sudo apt-get remove -y libc6-dev
sudo apt-get remove -y locales
sudo apt-get remove -y systemd
sudo apt-get remove -y perl-modules-5.32
sudo apt-get remove -y aspnetcore-runtime-3.1
sudo apt-get remove -y coreutils
sudo apt-get remove -y libruby2.7
sudo apt-get remove -y libstdc++-10-dev
sudo apt-get remove -y emacs-nox
sudo apt-get remove -y aspnetcore-runtime-5.0
sudo apt-get remove -y lxc
sudo apt-get remove -y netstandard-targeting-pack-2.1
sudo apt-get remove -y aspnetcore-runtime-6.0
sudo apt-get remove -y libgtk2.0-common
sudo apt-get remove -y docker-ce-rootless-extras
sudo apt-get remove -y libpython3.9-dev
sudo apt-get remove -y iso-codes
sudo apt-get remove -y google-cloud-sdk-local-extract
sudo apt-get remove -y libz3-4
sudo apt-get remove -y mysql-community-client-core
sudo apt-get remove -y cmake
sudo apt-get remove -y clangd-9
sudo apt-get remove -y dotnet-targeting-pack-3.1
sudo apt-get remove -y cpp-10
sudo apt-get remove -y adwaita-icon-theme
sudo apt-get remove -y gcsfuse
sudo apt-get remove -y dotnet-targeting-pack-6.0
sudo apt-get remove -y g++-10
sudo apt-get remove -y libperl5.32
sudo apt-get remove -y dotnet-targeting-pack-5.0
sudo apt-get remove -y vim-runtime
sudo apt-get remove -y libicu67
sudo apt-get remove -y gh
sudo apt-get remove -y libgl1-mesa-dri
sudo apt-get remove -y git
sudo apt-get remove -y google-cloud-sdk
sudo apt-get remove -y dotnet-sdk-6.0
sudo apt-get remove -y qemu-user-static
sudo apt-get remove -y dotnet-sdk-2.1
sudo apt-get remove -y openjdk-17-jdk-headless
sudo apt-get remove -y dotnet-sdk-5.0
sudo apt-get remove -y openjdk-11-jdk-headless
sudo apt-get remove -y dotnet-sdk-3.1
sudo apt-get remove -y openjdk-17-jre-headless
sudo apt-get remove -y powershell
sudo apt-get remove -y openjdk-11-jre-headless
sudo apt-get remove -y docker-ce-cli
sudo apt-get remove -y packer
sudo apt-get remove -y google-cloud-sdk-app-engine-python-extras
sudo apt-get remove -y containerd.io
sudo apt-get remove -y openjdk-8-jre-headless
sudo apt-get remove -y libllvm11
sudo apt-get remove -y openjdk-8-jdk-headless
sudo apt-get remove -y google-cloud-sdk-datastore-emulator
sudo apt-get remove -y google-cloud-sdk-app-engine-python
sudo apt-get remove -y google-cloud-sdk-kpt
sudo apt-get remove -y mysql-community-client
sudo apt-get remove -y kubectl
sudo apt-get remove -y libclang-common-9-dev
sudo apt-get remove -y postgresql-14
sudo apt-get remove -y gcc-10
sudo apt-get remove -y google-cloud-sdk-minikube
sudo apt-get remove -y google-cloud-sdk-app-engine-java
sudo apt-get remove -y terraform
sudo apt-get remove -y google-cloud-sdk-skaffold
sudo apt-get remove -y google-cloud-sdk-pubsub-emulator
sudo apt-get remove -y dotnet-runtime-2.1
sudo apt-get remove -y dotnet-runtime-5.0
sudo apt-get remove -y dotnet-runtime-6.0
sudo apt-get remove -y emacs-common
sudo apt-get remove -y libllvm9
sudo apt-get remove -y aspnetcore-runtime-2.1
sudo apt-get remove -y dotnet-runtime-3.1
